#!/bin/sh
# ── jail-claude.sh ───────────────────────────────────────────────
#
# Build a Landlock-enforced sandbox for Claude Code.
#
# Finds the claude binary on your system, packages it with codejail,
# writes a JailFile tuned for Claude Code's actual runtime needs,
# and outputs the command to run it.
#
# Usage:
#   ./demo/jail-claude.sh [work-dir]
#
#   work-dir: directory Claude Code will operate in (default: cwd)
#
# Requirements:
#   - Linux 5.13+ with Landlock enabled
#   - Rust toolchain (to build codejail)
#   - Claude Code installed (npm i -g @anthropic-ai/claude-code)
# ─────────────────────────────────────────────────────────────────

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
DIM='\033[2m'
BOLD='\033[1m'
RESET='\033[0m'

die() { printf "${RED}error:${RESET} %s\n" "$1" >&2; exit 1; }
info() { printf "${CYAN}[jail-claude]${RESET} %s\n" "$1"; }

# ── Parse args ───────────────────────────────────────────────────

WORK_DIR="${1:-$(pwd)}"
WORK_DIR="$(cd "$WORK_DIR" && pwd)"  # resolve to absolute

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
JAIL_DIR="$WORK_DIR/.codejail"
HOME_DIR="$HOME"

# ── Find Claude Code binary ─────────────────────────────────────

info "finding claude binary..."

CLAUDE_BIN=""
if command -v claude >/dev/null 2>&1; then
    CLAUDE_BIN="$(readlink -f "$(command -v claude)")"
fi

if [ -z "$CLAUDE_BIN" ] || [ ! -x "$CLAUDE_BIN" ]; then
    # Check common install locations
    for candidate in \
        "$HOME/.local/bin/claude" \
        "$HOME/.npm-global/bin/claude" \
        "/usr/local/bin/claude" \
        "/usr/bin/claude"; do
        if [ -x "$candidate" ]; then
            CLAUDE_BIN="$(readlink -f "$candidate")"
            break
        fi
    done
fi

[ -n "$CLAUDE_BIN" ] && [ -x "$CLAUDE_BIN" ] || \
    die "claude not found. install with: npm i -g @anthropic-ai/claude-code"

CLAUDE_VERSION=$("$CLAUDE_BIN" --version 2>/dev/null || echo "unknown")
info "found: $CLAUDE_BIN ($CLAUDE_VERSION)"

# ── Build codejail ───────────────────────────────────────────────

info "building codejail..."
cargo build --release --manifest-path "$REPO_ROOT/Cargo.toml" 2>/dev/null
CODEJAIL="$REPO_ROOT/target/release/codejail"
[ -x "$CODEJAIL" ] || die "build failed"
info "built: $CODEJAIL"

# ── Check Landlock support ───────────────────────────────────────

# Quick probe: landlock_create_ruleset with version flag
if ! "$CODEJAIL" --version >/dev/null 2>&1; then
    die "codejail binary not functional"
fi

# ── Create jail artifacts ────────────────────────────────────────

info "creating jail in $JAIL_DIR"
mkdir -p "$JAIL_DIR"

# Generate bridge.wasm via codejail make (we only need the bridge module)
TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

CODEJAIL_HOME="$TMPDIR/home" "$CODEJAIL" make "$CLAUDE_BIN" -o "$TMPDIR/gen" 2>/dev/null

cp "$TMPDIR/gen.d/bridge.wasm" "$JAIL_DIR/bridge.wasm"

# ── Write JailFile ───────────────────────────────────────────────
#
# This JailFile was derived through iterative strace analysis of
# Claude Code's actual runtime needs. Each entry exists because
# Landlock denied it and Claude Code crashed without it.

info "writing JailFile.toml..."

# Detect git repo root for the working directory (if any)
GIT_DIR=""
if command -v git >/dev/null 2>&1; then
    GIT_DIR="$(cd "$WORK_DIR" && git rev-parse --show-toplevel 2>/dev/null || true)"
fi

# Build fs_read entries — system paths needed by any native ELF binary
# plus application-specific paths discovered via strace
cat > "$JAIL_DIR/JailFile.toml" << TOML_EOF
# JailFile for Claude Code — Landlock-enforced sandbox
#
# Generated by jail-claude.sh
# Claude: $CLAUDE_BIN ($CLAUDE_VERSION)
# Work:   $WORK_DIR
#
# This grants Claude Code access to operate in the working directory
# while blocking access to everything else in \$HOME.
#
# Edit this file to tighten or relax permissions.

[sandbox]
name = "claude-jailed"
entrypoint = "bridge.wasm"

[capabilities]
fs_read = [
    # ELF runtime — dynamic linker, shared libraries
    "/lib",
    "/lib64",
    "/usr/lib",
    "/usr/lib64",
    "/etc/ld.so.cache",
    # System — /etc/localtime→/usr/share/zoneinfo, /etc/resolv.conf→/run/systemd/resolve
    "/bin",
    "/usr/bin",
    "/usr/share",
    "/etc",
    "/run/systemd",
    # Kernel interfaces — /proc/self is per-process, need all of /proc
    "/proc",
    "/sys",
TOML_EOF

# Add git repo root if detected and different from work dir
if [ -n "$GIT_DIR" ] && [ "$GIT_DIR" != "$WORK_DIR" ]; then
    cat >> "$JAIL_DIR/JailFile.toml" << TOML_EOF
    # Git repo (parent of working dir — read-only)
    "$GIT_DIR",
TOML_EOF
fi

# Add gitconfig if it exists
if [ -f "$HOME_DIR/.gitconfig" ]; then
    cat >> "$JAIL_DIR/JailFile.toml" << TOML_EOF
    # Global git config
    "$HOME_DIR/.gitconfig",
TOML_EOF
fi

# Add the claude binary itself
cat >> "$JAIL_DIR/JailFile.toml" << TOML_EOF
    # Claude Code binary
    "$CLAUDE_BIN",
]
fs_write = [
    # Device nodes — programs need /dev/null, /dev/tty writes
    "/dev",
    # Scratch space
    "/tmp",
    # Claude Code config and state
    "$HOME_DIR/.claude",
    "$HOME_DIR/.claude.json",
    "$HOME_DIR/.config",
    "$HOME_DIR/.npm",
    # Working directory — where Claude Code operates
    "$WORK_DIR",
]
net_allow = []
env = [
    "HOME",
    "LANG",
    "PATH",
    "TERM",
    "USER",
]
inherit_env = false
stdin = true
stdout = true
stderr = true

[limits]
memory_mb = 512
fuel = 0
wall_time_secs = 0
TOML_EOF

info "JailFile written: $JAIL_DIR/JailFile.toml"

# ── Write launcher script ────────────────────────────────────────

LAUNCHER="$JAIL_DIR/run"
cat > "$LAUNCHER" << LAUNCHER_EOF
#!/bin/sh
set -e
JAIL_DIR="$JAIL_DIR"
exec "$CODEJAIL" run \\
    --native-exec "$CLAUDE_BIN" \\
    --jailfile "\$JAIL_DIR/JailFile.toml" \\
    --fuel 0 --timeout 0 \\
    "\$JAIL_DIR/bridge.wasm" \\
    -- "\$@"
LAUNCHER_EOF
chmod +x "$LAUNCHER"

# ── Summary ──────────────────────────────────────────────────────

printf "\n${BOLD}${GREEN}Sandbox ready.${RESET}\n\n"
printf "  ${BOLD}Run Claude Code in jail:${RESET}\n"
printf "    ${CYAN}$LAUNCHER${RESET}\n\n"
printf "  ${BOLD}Edit permissions:${RESET}\n"
printf "    ${DIM}$JAIL_DIR/JailFile.toml${RESET}\n\n"
printf "  ${BOLD}What's allowed:${RESET}\n"
printf "    ${GREEN}rw${RESET}  $WORK_DIR\n"
printf "    ${GREEN}rw${RESET}  ~/.claude, ~/.config, /tmp\n"
printf "    ${DIM}ro${RESET}  system libs, /proc, /sys, /etc\n\n"
printf "  ${BOLD}What's blocked:${RESET}\n"
printf "    ${RED}--${RESET}  Everything else in \$HOME\n"
printf "    ${RED}--${RESET}  Other users' directories\n"
printf "    ${RED}--${RESET}  Any path not listed above\n\n"
