use std::path::Path;

use clap::{Parser, Subcommand};

mod analyzer;
mod capability;
mod container;
mod image;
mod make;
mod native_bridge;
mod policy;
mod runtime;
mod sandbox;

#[derive(Parser)]
#[command(
    name = "codejail",
    version,
    about = "WASM sandbox with Docker-like commands.\n\n\
             Run untrusted code with deny-by-default capabilities.\n\
             Grant filesystem, network, and environment access explicitly."
)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
#[allow(clippy::large_enum_variant)]
enum Commands {
    /// Run a WASM module in a capability-restricted sandbox
    Run {
        /// WASM module path or image name
        image: String,

        /// Capability grants: fs:read:/path, fs:write:/path, fs:/path, net:host:port, env:VAR
        #[arg(long = "cap")]
        caps: Vec<String>,

        /// Run detached (background)
        #[arg(short = 'd', long)]
        detach: bool,

        /// Container name
        #[arg(long)]
        name: Option<String>,

        /// JailFile path for capability manifest
        #[arg(short = 'f', long = "jailfile")]
        jailfile: Option<String>,

        /// CPU fuel limit (0 = unlimited)
        #[arg(long, default_value = "1000000000")]
        fuel: u64,

        /// Wall-clock timeout in seconds (0 = unlimited)
        #[arg(long, default_value = "300")]
        timeout: u64,

        /// Enable all network access
        #[arg(long)]
        net: bool,

        /// Mount volume host_path:guest_path (or just path for same)
        #[arg(short = 'v', long = "volume")]
        volumes: Vec<String>,

        /// Set environment variable (KEY=VALUE or KEY to inherit from host)
        #[arg(short = 'e', long = "env")]
        env_vars: Vec<String>,

        /// Wrap in bubblewrap outer sandbox (defense in depth)
        #[arg(long)]
        bwrap: bool,

        /// Policy file for capability authorization (enables policy mode)
        #[arg(long)]
        policy: Option<String>,

        /// Declared intent for behavioral drift detection
        #[arg(long, default_value = "general")]
        intent: String,

        /// Audit log path
        #[arg(long)]
        audit_log: Option<String>,

        /// Native binary path for bridge mode (generated by `codejail make`)
        #[arg(long)]
        native_exec: Option<String>,

        /// Arguments passed to the WASM module (or native binary in bridge mode)
        #[arg(last = true)]
        args: Vec<String>,
    },

    /// Package a native binary into a WASM-supervised sandbox
    Make {
        /// Path to the native binary to package
        binary: String,

        /// Output name for the launcher (creates <name> script and <name>.d/ directory)
        #[arg(short = 'o', long = "output", default_value = "jailed")]
        output: String,

        /// Only analyze the binary, don't generate artifacts
        #[arg(long)]
        analyze_only: bool,

        /// Generate permissive capabilities (inherit all env, allow all network)
        #[arg(long)]
        permissive: bool,
    },

    /// List containers
    Ps {
        /// Show all (including stopped/failed)
        #[arg(short = 'a', long)]
        all: bool,
    },

    /// Stop a running container
    Stop {
        /// Container ID, short ID, or name
        id: String,
    },

    /// Remove a stopped container
    Rm {
        /// Container ID, short ID, or name
        id: String,
    },

    /// Remove all stopped containers
    Prune,

    /// List images in the local store
    Images,

    /// Import a .wasm file as a named image
    Import {
        /// Image name
        name: String,
        /// Path to .wasm file
        path: String,
    },

    /// Remove an image
    Rmi {
        /// Image name
        name: String,
    },

    /// Inspect a WASM module (show exports, imports, size)
    Inspect {
        /// Image name or .wasm path
        image: String,
    },

    /// Build from a JailFile.toml
    Build {
        /// Build context directory
        #[arg(default_value = ".")]
        context: String,

        /// JailFile path (relative to context)
        #[arg(short = 'f', long, default_value = "JailFile.toml")]
        file: String,
    },

    /// Show sandbox capabilities and system info
    Info,
}

fn main() -> anyhow::Result<()> {
    let cli = Cli::parse();
    match cli.command {
        Commands::Run {
            image,
            caps,
            detach,
            name,
            jailfile,
            fuel,
            timeout,
            net,
            volumes,
            env_vars,
            bwrap,
            policy,
            intent,
            audit_log,
            native_exec,
            args,
        } => cmd_run(RunArgs {
            image,
            caps,
            _detach: detach,
            name,
            jailfile,
            fuel,
            timeout,
            net,
            volumes,
            env_vars,
            bwrap,
            policy,
            intent,
            audit_log,
            native_exec,
            args,
        }),
        Commands::Make {
            binary,
            output,
            analyze_only,
            permissive,
        } => {
            let config = make::MakeConfig {
                binary_path: std::path::PathBuf::from(binary),
                output_name: output,
                analyze_only,
                permissive,
            };
            make::cmd_make(config)?;
            Ok(())
        }
        Commands::Ps { all } => cmd_ps(all),
        Commands::Stop { id } => cmd_stop(&id),
        Commands::Rm { id } => cmd_rm(&id),
        Commands::Prune => cmd_prune(),
        Commands::Images => cmd_images(),
        Commands::Import { name, path } => cmd_import(&name, &path),
        Commands::Rmi { name } => cmd_rmi(&name),
        Commands::Inspect { image } => cmd_inspect(&image),
        Commands::Build { context, file } => cmd_build(&context, &file),
        Commands::Info => cmd_info(),
    }
}

struct RunArgs {
    image: String,
    caps: Vec<String>,
    _detach: bool,
    name: Option<String>,
    jailfile: Option<String>,
    fuel: u64,
    timeout: u64,
    net: bool,
    volumes: Vec<String>,
    env_vars: Vec<String>,
    bwrap: bool,
    policy: Option<String>,
    intent: String,
    audit_log: Option<String>,
    native_exec: Option<String>,
    args: Vec<String>,
}

fn cmd_run(a: RunArgs) -> anyhow::Result<()> {
    // Resolve image path
    let image_store = image::ImageStore::new()?;
    let wasm_path = image_store.resolve(&a.image)?;

    // Parse --cap grants
    let mut grants = Vec::new();
    for s in &a.caps {
        grants.push(capability::CapGrant::parse(s)?);
    }

    // Load base capabilities from JailFile or defaults
    let base_caps = if let Some(jf_path) = &a.jailfile {
        let content = std::fs::read_to_string(jf_path)?;
        let jf: capability::JailFile = toml::from_str(&content)?;
        jf.capabilities
    } else {
        capability::Capabilities {
            stdin: true,
            stdout: true,
            stderr: true,
            ..Default::default()
        }
    };

    // Determine policy path (flag > env > none)
    let policy_path_opt = a.policy.or_else(|| std::env::var("POLICY_FILE").ok());

    // Resolve capabilities: either through policy evaluation or self-authorization
    let resolved = if let Some(policy_path) = &policy_path_opt {
        // Policy mode: evaluate each capability against policy
        eprintln!("[codejail] policy mode: {policy_path}");
        let gate = policy::PolicyGate::load(
            Path::new(policy_path),
            a.audit_log.as_deref().map(Path::new),
        )?;

        let rt = tokio::runtime::Runtime::new()?;
        let verdict = rt.block_on(gate.evaluate_caps(
            &a.image,
            &a.intent,
            &grants,
            &a.volumes,
            &a.env_vars,
            a.net,
            if a.fuel == 0 {
                1000
            } else {
                a.fuel / 1_000_000
            },
            a.timeout,
        ))?;

        // Print policy decisions
        for d in &verdict.decisions {
            let icon = if d.allowed { "+" } else { "x" };
            eprintln!("[codejail]   [{icon}] {}: {}", d.tool_name, d.reason);
        }
        if verdict.denied_count > 0 {
            eprintln!(
                "[codejail] policy denied {} of {} capability requests",
                verdict.denied_count,
                verdict.decisions.len()
            );
        }
        eprintln!(
            "[codejail] session {} (agent {}, intent: '{}')",
            verdict.session.session_id, verdict.agent.id, a.intent
        );

        verdict.authorized_caps
    } else {
        // Self-authorization mode: existing behavior
        capability::ResolvedCaps::from_parts(&base_caps, &grants, &a.volumes, &a.env_vars, a.net)
    };

    let limits = capability::Limits {
        fuel: if a.fuel == 0 { None } else { Some(a.fuel) },
        wall_time_secs: Some(a.timeout),
        memory_mb: Some(256),
    };

    // Check bwrap if requested
    if a.bwrap && !sandbox::bwrap_available() {
        anyhow::bail!("--bwrap requested but bubblewrap is not installed");
    }

    // Create container record
    let container_name = a.name.unwrap_or_else(|| {
        let stem = wasm_path.file_stem().unwrap_or_default().to_string_lossy();
        format!("{stem}-{}", &uuid::Uuid::new_v4().to_string()[..8])
    });
    let mut ctr = container::Container::new(&container_name, &a.image, &a.caps);
    let store = container::ContainerStore::new()?;

    // Print container ID (like docker)
    println!("{}", ctr.short_id);

    // Print capability summary
    eprintln!("[codejail] Sandbox: {}", container_name);
    eprintln!("[codejail] Image:   {}", wasm_path.display());
    if !resolved.fs_mounts.is_empty() {
        for m in &resolved.fs_mounts {
            let mode = if m.writable { "rw" } else { "ro" };
            eprintln!(
                "[codejail]   fs: {} -> {} ({})",
                m.host.display(),
                m.guest,
                mode
            );
        }
    }
    if !resolved.net_rules.is_empty() {
        eprintln!("[codejail]   net: {:?}", resolved.net_rules);
    }
    if resolved.fs_mounts.is_empty() && resolved.net_rules.is_empty() {
        eprintln!("[codejail]   (no capabilities granted, fully isolated)");
    }
    eprintln!();

    // Run — either native bridge mode or standard WASM mode
    if let Some(ref native_binary) = a.native_exec {
        // Native bridge mode: WASM supervisor + native binary execution
        eprintln!("[codejail] native bridge mode: {native_binary}");
        let bridge_runtime = native_bridge::NativeBridgeRuntime::new()?;

        let native_config = native_bridge::NativeExecConfig {
            binary_path: std::path::PathBuf::from(native_binary),
            args: a.args.clone(),
            env_vars: resolved.env_vars.clone(),
            cwd: None,
            inherit_env: base_caps.inherit_env,
        };

        match bridge_runtime.run(&wasm_path, native_config, &a.args) {
            Ok(exit_code) => {
                ctr.status = container::ContainerStatus::Exited(exit_code);
                store.save(&ctr)?;
                if exit_code != 0 {
                    std::process::exit(exit_code);
                }
            }
            Err(e) => {
                ctr.status = container::ContainerStatus::Failed(e.to_string());
                store.save(&ctr)?;
                return Err(e);
            }
        }
    } else {
        // Standard WASM mode
        let rt = runtime::SandboxRuntime::new(limits.fuel.is_some())?;
        match rt.run(&wasm_path, &resolved, &limits, &a.args) {
            Ok(()) => {
                ctr.status = container::ContainerStatus::Exited(0);
                store.save(&ctr)?;
            }
            Err(e) => {
                ctr.status = container::ContainerStatus::Failed(e.to_string());
                store.save(&ctr)?;
                return Err(e);
            }
        }
    }
    Ok(())
}

fn cmd_ps(all: bool) -> anyhow::Result<()> {
    let store = container::ContainerStore::new()?;
    let containers = store.list()?;

    println!(
        "{:<14} {:<20} {:<20} {:<22} IMAGE",
        "CONTAINER ID", "NAME", "STATUS", "CREATED"
    );
    for c in &containers {
        if !all && !matches!(c.status, container::ContainerStatus::Running) {
            continue;
        }
        println!(
            "{:<14} {:<20} {:<20} {:<22} {}",
            c.short_id,
            truncate(&c.name, 18),
            c.status,
            c.created.format("%Y-%m-%d %H:%M:%S"),
            c.image
        );
    }
    if containers.is_empty() {
        eprintln!("No containers found. Run one with: codejail run <image.wasm>");
    }
    Ok(())
}

fn cmd_stop(id: &str) -> anyhow::Result<()> {
    let store = container::ContainerStore::new()?;
    let mut c = store.load(id)?;
    if let Some(pid) = c.pid {
        let _ = nix::sys::signal::kill(
            nix::unistd::Pid::from_raw(pid as i32),
            nix::sys::signal::Signal::SIGTERM,
        );
    }
    c.status = container::ContainerStatus::Exited(137);
    store.save(&c)?;
    println!("{}", c.short_id);
    Ok(())
}

fn cmd_rm(id: &str) -> anyhow::Result<()> {
    let store = container::ContainerStore::new()?;
    let c = store.load(id)?;
    if matches!(c.status, container::ContainerStatus::Running) {
        anyhow::bail!(
            "Cannot remove running container {}. Stop it first.",
            c.short_id
        );
    }
    store.remove(&c.id)?;
    println!("{}", c.short_id);
    Ok(())
}

fn cmd_prune() -> anyhow::Result<()> {
    let store = container::ContainerStore::new()?;
    let count = store.prune()?;
    println!("Removed {count} stopped container(s)");
    Ok(())
}

fn cmd_images() -> anyhow::Result<()> {
    let store = image::ImageStore::new()?;
    let images = store.list()?;

    println!("{:<20} {:<12} PATH", "NAME", "SIZE");
    for img in &images {
        println!(
            "{:<20} {:<12} {}",
            img.name,
            human_size(img.size),
            img.path.display()
        );
    }
    if images.is_empty() {
        eprintln!("No images. Import one with: codejail import <name> <path.wasm>");
    }
    Ok(())
}

fn cmd_import(name: &str, path: &str) -> anyhow::Result<()> {
    let store = image::ImageStore::new()?;
    let img = store.import(name, Path::new(path))?;
    println!("Imported: {} ({})", img.name, human_size(img.size));
    Ok(())
}

fn cmd_rmi(name: &str) -> anyhow::Result<()> {
    let store = image::ImageStore::new()?;
    store.remove(name)?;
    println!("Removed: {name}");
    Ok(())
}

fn cmd_inspect(image: &str) -> anyhow::Result<()> {
    let store = image::ImageStore::new()?;
    let path = store.resolve(image)?;
    let info = runtime::inspect_module(&path)?;

    println!("Image:   {image}");
    println!("Path:    {}", path.display());
    println!("Size:    {}", human_size(info.size));
    println!();
    println!("Exports ({}):", info.exports.len());
    for e in &info.exports {
        println!("  {e}");
    }
    println!();
    println!("Imports ({}):", info.imports.len());
    for i in &info.imports {
        println!("  {i}");
    }
    Ok(())
}

fn cmd_build(context: &str, file: &str) -> anyhow::Result<()> {
    let jailfile_path = Path::new(context).join(file);
    anyhow::ensure!(
        jailfile_path.exists(),
        "JailFile not found: {}",
        jailfile_path.display()
    );

    let content = std::fs::read_to_string(&jailfile_path)?;
    let jf: capability::JailFile = toml::from_str(&content)?;

    let entrypoint = Path::new(context).join(&jf.sandbox.entrypoint);
    anyhow::ensure!(
        entrypoint.exists(),
        "Entrypoint not found: {}",
        entrypoint.display()
    );

    let image_name = jf.sandbox.name.unwrap_or_else(|| {
        entrypoint
            .file_stem()
            .unwrap_or_default()
            .to_string_lossy()
            .to_string()
    });

    // If it's a Rust source file, compile to WASM
    if entrypoint.extension().is_some_and(|e| e == "rs") {
        println!(
            "[codejail] Compiling {} -> wasm32-wasip1...",
            entrypoint.display()
        );
        let wasm_out = entrypoint.with_extension("wasm");
        let output = std::process::Command::new("rustc")
            .args(["--target", "wasm32-wasip1", "--edition", "2021", "-o"])
            .arg(&wasm_out)
            .arg(&entrypoint)
            .output()?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            anyhow::bail!("Compilation failed:\n{stderr}");
        }
        println!("[codejail] Compiled: {}", wasm_out.display());

        let store = image::ImageStore::new()?;
        let img = store.import(&image_name, &wasm_out)?;
        println!(
            "[codejail] Image '{}' ready ({})",
            img.name,
            human_size(img.size)
        );
    } else if entrypoint.extension().is_some_and(|e| e == "wasm") {
        let store = image::ImageStore::new()?;
        let img = store.import(&image_name, &entrypoint)?;
        println!(
            "[codejail] Image '{}' ready ({})",
            img.name,
            human_size(img.size)
        );
    } else {
        anyhow::bail!(
            "Don't know how to build '{}'. Supported: .rs, .wasm",
            jf.sandbox.entrypoint
        );
    }

    Ok(())
}

fn cmd_info() -> anyhow::Result<()> {
    println!("codejail {}", env!("CARGO_PKG_VERSION"));
    println!();
    println!("Runtime:     wasmtime 43");
    println!("WASI:        preview 1 (wasm32-wasip1)");
    println!("Data dir:    {}", container::codejail_home().display());
    println!(
        "Bubblewrap:  {}",
        if sandbox::bwrap_available() {
            "available"
        } else {
            "not found"
        }
    );
    println!();

    // Check wasm target
    let has_target = std::process::Command::new("rustup")
        .args(["target", "list", "--installed"])
        .output()
        .map(|o| String::from_utf8_lossy(&o.stdout).contains("wasm32-wasip1"))
        .unwrap_or(false);
    println!(
        "wasm32-wasip1 target: {}",
        if has_target {
            "installed"
        } else {
            "not installed (run: rustup target add wasm32-wasip1)"
        }
    );

    println!();
    println!("Capability model: deny-by-default");
    println!("  --cap fs:read:/path    Grant read access to directory");
    println!("  --cap fs:write:/path   Grant write access to directory");
    println!("  --cap fs:/path         Grant read+write access");
    println!("  --cap net:host:port    Allow network to specific destination");
    println!("  --cap net:*            Allow all network access");
    println!("  --cap env:VAR1,VAR2    Pass environment variables");
    println!("  -v host:guest          Mount directory (read+write)");
    println!("  -e KEY=VALUE           Set environment variable");
    println!("  --net                  Allow all network access");
    println!("  --bwrap                Enable bubblewrap outer sandbox");
    Ok(())
}

fn human_size(bytes: u64) -> String {
    if bytes >= 1_000_000 {
        format!("{:.1} MB", bytes as f64 / 1_000_000.0)
    } else if bytes >= 1_000 {
        format!("{:.1} KB", bytes as f64 / 1_000.0)
    } else {
        format!("{bytes} B")
    }
}

fn truncate(s: &str, max: usize) -> String {
    if s.len() > max {
        format!("{}...", &s[..max - 3])
    } else {
        s.to_string()
    }
}
